#ifndef CO_LEX_H
#define CO_LEX_H

#include "global.h"

enum state_type{
	STAT_START,
	STAT_IDENT,
	STAT_INT,STAT_DBL,STAT_FLT,STAT_UINT,STAT_ULONG,STAT_LONG,STAT_SHORT,STAT_USHORT,
	STAT_CHAR1,STAT_CHAR2,STAT_CHAR3,STAT_CHAR4,STAT_CHAR5,
	STAT_STR1,STAT_STR2,STAT_STR3,STAT_STR4,
	STAT_SMBL,
	STAT_PLUS,STAT_INCR,
	STAT_SUB,STAT_DECR,
	STAT_BAND,STAT_AND,
	STAT_BOR,STAT_OR,
	STAT_NOT,STAT_NE,
	STAT_ASGN,STAT_EQ,
	STAT_GT,STAT_SR,STAT_GE,
	STAT_LT,STAT_SL,STAT_LE,
	STAT_BLANK,
	STAT_MUL,STAT_DIV,STAT_MOD,
	STAT_ADDASS,STAT_SUBASS,STAT_MODASS,STAT_MULASS,STAT_DIVASS,
	STAT_COMMA,STAT_SEMICOLON,
	STAT_LPARE,STAT_RPARE,STAT_LBRACKET,STAT_RBRACKET,STAT_LBRACE,STAT_RBRACE,
	STAT_XOR,STAT_QM,STAT_COLON,
	STAT_BITNOT,STAT_LOGINOT,
	STAT_BITOR,
	STAT_SHLASS,STAT_SHRASS,
};


int get_token(std::string s, bool use_blank);

#endif //CO_LEX_H
